server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1iye66n7rmxt3t1ro.mysql.rds.aliyuncs.com/graduation?characterEncoding=utf-8&useSSL=false
    username: black
    password: Black2021

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.black.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true